name: Set up a minicube cluster

on:
  pull_request:
    types: [opened, reopened]

jobs:
  set_up_minikube_cluster:
    runs-on: ubuntu-latest
    steps:
      - name: start minikube
        id: minikube
        uses: medyagh/setup-minikube@latest
      - name: Testing
        run: |
          kubectl cluster-info --context minicube
          kubectl version
          kubectl get pods -A
          kubectl get nodes
